
/*
To Run this script via any sort of SQL Editor, make sure that '/' is set as the statement delimiter, not ';'
since ';' characters must be inlcluded in the triggers themselves.
*/
	
CREATE OR REPLACE TRIGGER MODEL_REACH_AUTO_ID_TRIG
BEFORE INSERT ON MODEL_REACH
REFERENCING NEW AS newRow
FOR EACH ROW WHEN (newRow.MODEL_REACH_ID IS NULL)
BEGIN
	SELECT MODEL_REACH_SEQ.nextval INTO :newRow.MODEL_REACH_ID FROM dual;
END;
/


CREATE OR REPLACE TRIGGER REACH_COEF_AUTO_ID_TRIG
BEFORE INSERT ON REACH_COEF
REFERENCING NEW AS newRow
FOR EACH ROW WHEN (newRow.REACH_COEF_ID IS NULL)
BEGIN
	SELECT REACH_COEF_SEQ.nextval INTO :newRow.REACH_COEF_ID FROM dual;
END;
/


CREATE OR REPLACE TRIGGER SOURCE_AUTO_ID_TRIG
BEFORE INSERT ON SOURCE
REFERENCING NEW AS newRow
FOR EACH ROW WHEN (newRow.SOURCE_ID IS NULL)
BEGIN
	SELECT SOURCE_SEQ.nextval INTO :newRow.SOURCE_ID FROM dual;
END;
/


CREATE OR REPLACE TRIGGER SOURCE_REACH_COEF_AUTO_ID_TRIG
BEFORE INSERT ON SOURCE_REACH_COEF
REFERENCING NEW AS newRow
FOR EACH ROW WHEN (newRow.SOURCE_REACH_COEF_ID IS NULL)
BEGIN
	SELECT SOURCE_REACH_COEF_SEQ.nextval INTO :newRow.SOURCE_REACH_COEF_ID FROM dual;
END;
/


CREATE OR REPLACE TRIGGER SOURCE_REACH_PREDICT_AUTO_ID_TRIG
BEFORE INSERT ON SOURCE_REACH_PREDICT
REFERENCING NEW AS newRow
FOR EACH ROW WHEN (newRow.SOURCE_REACH_PREDICT_ID IS NULL)
BEGIN
	SELECT SOURCE_REACH_PREDICT_SEQ.nextval INTO :newRow.SOURCE_REACH_PREDICT_ID FROM dual;
END;
/


CREATE OR REPLACE TRIGGER SOURCE_VALUE_AUTO_ID_TRIG
BEFORE INSERT ON SOURCE_VALUE
REFERENCING NEW AS newRow
FOR EACH ROW WHEN (newRow.SOURCE_VALUE_ID IS NULL)
BEGIN
	SELECT SOURCE_VALUE_SEQ.nextval INTO :newRow.SOURCE_VALUE_ID FROM dual;
END;
/


CREATE OR REPLACE TRIGGER SPARROW_MODEL_AUTO_ID_TRIG
BEFORE INSERT ON SPARROW_MODEL
REFERENCING NEW AS newRow
FOR EACH ROW WHEN (newRow.SPARROW_MODEL_ID IS NULL)
BEGIN
	SELECT SPARROW_MODEL_SEQ.nextval INTO :newRow.SPARROW_MODEL_ID FROM dual;
END;
/


CREATE OR REPLACE TRIGGER TOTAL_PREDICT_AUTO_ID_TRIG
BEFORE INSERT ON TOTAL_PREDICT
REFERENCING NEW AS newRow
FOR EACH ROW WHEN (newRow.TOTAL_PREDICT_ID IS NULL)
BEGIN
	SELECT TOTAL_PREDICT_SEQ.nextval INTO :newRow.TOTAL_PREDICT_ID FROM dual;
END;
/


COMMIT
/
	