CREATE TABLE CONTACT
(
CONTACT_ID NUMBER(9) NOT NULL,
FIRST_NAME VARCHAR2(60) NOT NULL,
LAST_NAME VARCHAR2(60) NOT NULL,
PERSON_PHONE VARCHAR2(60),
PERSON_EMAIL VARCHAR2(100),
ORG_NAME VARCHAR2(200) NOT NULL,
ORG_PHONE VARCHAR2(60),
ADDRESS VARCHAR2(400),
ADD_DATE DATE NOT NULL,
UPDATE_DATE DATE
)
;

CREATE TABLE ENH_NETWORK
(
ENH_NETWORK_ID NUMBER(9) NOT NULL,
NAME VARCHAR2(100) NOT NULL,
MAJOR_REV INT NOT NULL,
MINOR_REV INT NOT NULL,
REV_NAME VARCHAR2(30) NOT NULL,
DESCRIPTION CLOB,
IS_APPROVED CHAR(1) DEFAULT 'F' NOT NULL,
IS_PUBLIC CHAR(1) DEFAULT 'F' NOT NULL,
IS_ARCHIVED CHAR(1) DEFAULT 'F' NOT NULL,
NOM_NETWORK_ID NUMBER(9) NOT NULL,
NETWORK_AREA_ID NUMBER(9) NOT NULL,
CONTACT_ID NUMBER(9) NOT NULL
)
;

CREATE TABLE ENH_REACH
(
ENH_REACH_ID NUMBER(9) NOT NULL,
ENH_NETWORK_ID NUMBER(9) NOT NULL,
NOM_REACH_ID NUMBER(9),
IDENTIFIER NUMBER(9) NOT NULL,
FULL_IDENTIFIER VARCHAR2(40) NOT NULL
)
;

CREATE TABLE ENH_REACH_GEOM
(
ENH_REACH_ID NUMBER(9) NOT NULL,
REACH_GEOM MDSYS.SDO_GEOMETRY NOT NULL,
CATCH_GEOM MDSYS.SDO_GEOMETRY NOT NULL,
CUM_CATCH_GEOM MDSYS.SDO_GEOMETRY NOT NULL
)
;

CREATE TABLE ENH_REACH_TOPO
(
ENH_REACH_ID NUMBER(9) NOT NULL,
FNODE NUMBER(9),
TNODE NUMBER(9),
HYDSEQ FLOAT NOT NULL,
AIFTRAN FLOAT NOT NULL
)
;

CREATE TABLE NETWORK_AREA
(
NETWORK_AREA_ID NUMBER(9) NOT NULL,
NAME VARCHAR2(40) NOT NULL,
DESCRIPTION CLOB
)
;

CREATE TABLE NETWORK_TYPE
(
NETWORK_TYPE_ID NUMBER(9) NOT NULL,
NAME VARCHAR2(40) NOT NULL,
DESCRIPTION CLOB
)
;

CREATE TABLE NOM_NETWORK
(
NOM_NETWORK_ID NUMBER(9) NOT NULL,
NAME VARCHAR2(100) NOT NULL,
MAJOR_REV INT NOT NULL,
MINOR_REV INT NOT NULL,
REV_NAME VARCHAR2(30) NOT NULL,
DESCRIPTION CLOB,
IS_APPROVED CHAR(1) DEFAULT 'F' NOT NULL,
IS_PUBLIC CHAR(1) DEFAULT 'F' NOT NULL,
IS_ARCHIVED CHAR(1) DEFAULT 'F' NOT NULL,
NETWORK_AREA_ID NUMBER(9) NOT NULL,
NETWORK_TYPE_ID NUMBER(9) NOT NULL,
CONTACT_ID NUMBER(9) NOT NULL
)
;

CREATE TABLE NOM_REACH
(
NOM_REACH_ID NUMBER(9) NOT NULL,
NOM_NETWORK_ID NUMBER(9) NOT NULL,
IDENTIFIER NUMBER(9) NOT NULL,
FULL_IDENTIFIER VARCHAR2(40) NOT NULL,
FNODE NUMBER(7),
TNODE NUMBER(7),
HYDSEQ FLOAT NOT NULL,
AIFTRAN FLOAT DEFAULT 1 NOT NULL,
REACH_GEOM MDSYS.SDO_GEOMETRY,
CATCH_GEOM MDSYS.SDO_GEOMETRY,
CUM_CATCH_GEOM MDSYS.SDO_GEOMETRY
)
;

ALTER TABLE CONTACT
ADD CONSTRAINT CONTACT_PK PRIMARY KEY
(
CONTACT_ID
)
 ENABLE
;

ALTER TABLE ENH_NETWORK
ADD CONSTRAINT ENH_NETWORK_PK PRIMARY KEY
(
ENH_NETWORK_ID
)
 ENABLE
;

ALTER TABLE ENH_NETWORK
ADD CONSTRAINT ENH_NETWORK_UK_REVISION UNIQUE
(
NOM_NETWORK_ID,
NETWORK_AREA_ID,
IS_PUBLIC,
IS_APPROVED,
IS_ARCHIVED,
MAJOR_REV,
MINOR_REV
)
 ENABLE
;

ALTER TABLE ENH_REACH
ADD CONSTRAINT ENH_REACH_PK PRIMARY KEY
(
ENH_REACH_ID
)
 ENABLE
;

ALTER TABLE ENH_REACH
ADD CONSTRAINT ENH_REACH_UK_IDENTIFIER UNIQUE
(
ENH_NETWORK_ID,
IDENTIFIER
)
 ENABLE
;

ALTER TABLE ENH_REACH_GEOM
ADD CONSTRAINT ENH_REACH_GEOM_PK PRIMARY KEY
(
ENH_REACH_ID
)
 ENABLE
;

ALTER TABLE ENH_REACH_TOPO
ADD CONSTRAINT ENH_REACH_TOPO_PK PRIMARY KEY
(
ENH_REACH_ID
)
 ENABLE
;

ALTER TABLE NETWORK_AREA
ADD CONSTRAINT NETWORK_AREA_PK PRIMARY KEY
(
NETWORK_AREA_ID
)
 ENABLE
;

ALTER TABLE NETWORK_TYPE
ADD CONSTRAINT NETWORK_TYPE_PK PRIMARY KEY
(
NETWORK_TYPE_ID
)
 ENABLE
;

ALTER TABLE NOM_NETWORK
ADD CONSTRAINT NETWORK_PK PRIMARY KEY
(
NOM_NETWORK_ID
)
 ENABLE
;

ALTER TABLE NOM_NETWORK
ADD CONSTRAINT NOM_NETWORK_UK_REV UNIQUE
(
NETWORK_AREA_ID,
NETWORK_TYPE_ID,
IS_PUBLIC,
IS_APPROVED,
IS_ARCHIVED,
MAJOR_REV,
MINOR_REV
)
 ENABLE
;

ALTER TABLE NOM_REACH
ADD CONSTRAINT REACH_PK PRIMARY KEY
(
NOM_REACH_ID
)
 ENABLE
;

ALTER TABLE NOM_REACH
ADD CONSTRAINT NOM_REACH_UK_IDENTIFIER UNIQUE
(
NOM_NETWORK_ID,
IDENTIFIER
)
 ENABLE
;

ALTER TABLE NOM_REACH
ADD CONSTRAINT NOM_REACH_UK_HYDSEQ UNIQUE
(
NOM_NETWORK_ID,
HYDSEQ
)
 ENABLE
;

ALTER TABLE ENH_NETWORK
ADD CONSTRAINT ENH_NETWORK_NOM_NETWORK_FK FOREIGN KEY
(
NOM_NETWORK_ID
)
REFERENCES NOM_NETWORK
(
NOM_NETWORK_ID
) ENABLE
;

ALTER TABLE ENH_NETWORK
ADD CONSTRAINT ENH_NETWORK_NETWORK_AREA_FK FOREIGN KEY
(
NETWORK_AREA_ID
)
REFERENCES NETWORK_AREA
(
NETWORK_AREA_ID
) ENABLE
;

ALTER TABLE ENH_NETWORK
ADD CONSTRAINT ENH_NETWORK_CONTACT_FK FOREIGN KEY
(
CONTACT_ID
)
REFERENCES CONTACT
(
CONTACT_ID
) ENABLE
;

ALTER TABLE ENH_REACH
ADD CONSTRAINT ENH_REACH_ENH_NETWORK_FK FOREIGN KEY
(
ENH_NETWORK_ID
)
REFERENCES ENH_NETWORK
(
ENH_NETWORK_ID
) ENABLE
;

ALTER TABLE ENH_REACH
ADD CONSTRAINT ENH_REACH_NOM_REACH_FK FOREIGN KEY
(
NOM_REACH_ID
)
REFERENCES NOM_REACH
(
NOM_REACH_ID
) ENABLE
;

ALTER TABLE ENH_REACH_GEOM
ADD CONSTRAINT ENH_REACH_GEOM_ENH_REACH_FK FOREIGN KEY
(
ENH_REACH_ID
)
REFERENCES ENH_REACH
(
ENH_REACH_ID
) ENABLE
;

ALTER TABLE ENH_REACH_TOPO
ADD CONSTRAINT ENH_REACH_TOPO_ENH_REACH_FK FOREIGN KEY
(
ENH_REACH_ID
)
REFERENCES ENH_REACH
(
ENH_REACH_ID
) ENABLE
;

ALTER TABLE NOM_NETWORK
ADD CONSTRAINT NOM_NETWORK_NETWORK_AREA_FK FOREIGN KEY
(
NETWORK_AREA_ID
)
REFERENCES NETWORK_AREA
(
NETWORK_AREA_ID
) ENABLE
;

ALTER TABLE NOM_NETWORK
ADD CONSTRAINT NOM_NETWORK_NETWORK_TYPE_FK FOREIGN KEY
(
NETWORK_TYPE_ID
)
REFERENCES NETWORK_TYPE
(
NETWORK_TYPE_ID
) ENABLE
;

ALTER TABLE NOM_NETWORK
ADD CONSTRAINT NOM_NETWORK_CONTACT_FK FOREIGN KEY
(
CONTACT_ID
)
REFERENCES CONTACT
(
CONTACT_ID
) ENABLE
;

ALTER TABLE NOM_REACH
ADD CONSTRAINT NOM_REACH_NOM_NETWORK_FK FOREIGN KEY
(
NOM_NETWORK_ID
)
REFERENCES NOM_NETWORK
(
NOM_NETWORK_ID
) ENABLE
;

ALTER TABLE ENH_NETWORK
ADD CONSTRAINT ENH_NETWORK_CHK_IS_APP CHECK
(IS_APPROVED IN ('T','F'))
 ENABLE
;

ALTER TABLE ENH_NETWORK
ADD CONSTRAINT ENH_NETWORK_CHK_IS_PUBLIC CHECK
(IS_PUBLIC IN ('T', 'F'))
 ENABLE
;

ALTER TABLE ENH_NETWORK
ADD CONSTRAINT ENH_NETWORK_CHK_IS_ARC CHECK
(IS_ARCHIVED IN ('T', 'F'))
 ENABLE
;

ALTER TABLE NOM_NETWORK
ADD CONSTRAINT NOM_NETWORK_CHK_IS_APP CHECK
(IS_APPROVED IN ('T','F'))
 ENABLE
;

ALTER TABLE NOM_NETWORK
ADD CONSTRAINT NOM_NETWORK_CHK_IS_PUBLIC CHECK
(IS_PUBLIC IN ('T', 'F'))
 ENABLE
;

ALTER TABLE NOM_NETWORK
ADD CONSTRAINT NOM_NETWORK_CHK_IS_ARC CHECK
(IS_ARCHIVED IN ('T', 'F'))
 ENABLE
;

CREATE INDEX ENH_NETWORK_NOM_NETWORK_FK_I ON ENH_NETWORK (NOM_NETWORK_ID);

CREATE INDEX ENH_NETWORK_NETWORK_AREA_FK_I ON ENH_NETWORK (NETWORK_AREA_ID);

CREATE INDEX ENH_REACH_NOM_REACH_FK_I ON ENH_REACH (NOM_REACH_ID);

CREATE INDEX ENH_REACH_ENH_NETWORK_FK_I ON ENH_REACH (ENH_NETWORK_ID);

CREATE INDEX ENH_REACH_TOPO_HYDSEQ_I ON ENH_REACH_TOPO (HYDSEQ ASC);

CREATE INDEX NOM_REACH_NOM_NETWORK_FK_INDEX ON NOM_REACH (NOM_NETWORK_ID);

CREATE INDEX NOM_REACH_HYDSEQ_I ON NOM_REACH (HYDSEQ ASC);

CREATE SEQUENCE CONTACT_SEQ INCREMENT BY 1 START WITH 1 ORDER ;

CREATE SEQUENCE ENH_NETWORK_SEQ INCREMENT BY 1 START WITH 1 ORDER ;

CREATE SEQUENCE ENH_REACH_SEQ INCREMENT BY 1 START WITH 1 ORDER ;

CREATE SEQUENCE NETWORK_AREA_SEQ INCREMENT BY 1 START WITH 1 ORDER ;

CREATE SEQUENCE NETWORK_TYPE_SEQ INCREMENT BY 1 START WITH 1 ORDER ;

CREATE SEQUENCE NOM_NETWORK_SEQ INCREMENT BY 1 START WITH 1 ORDER ;

CREATE SEQUENCE NOM_REACH_SEQ INCREMENT BY 1 START WITH 1 ORDER ;

COMMENT ON COLUMN ENH_REACH_TOPO.FNODE IS 'Can be null b/c there may not be an upstream reach.'
;

COMMENT ON COLUMN ENH_REACH_TOPO.TNODE IS 'Can be null b/c there may not be a downstream reach.'
;

COMMENT ON COLUMN NOM_REACH.FNODE IS 'Can be null b/c there may not be an upstream reach.'
;

COMMENT ON COLUMN NOM_REACH.TNODE IS 'Can be null b/c there may not be a downstream reach.'
;

