CREATE TABLE MODEL_REACH
(
MODEL_REACH_ID NUMBER(9) NOT NULL,
IDENTIFIER NUMBER(9) NOT NULL,
FULL_IDENTIFIER VARCHAR2(40) NOT NULL,
SPARROW_MODEL_ID NUMBER(9, 0) NOT NULL,
ENH_REACH_ID NUMBER(9)
)
;

CREATE TABLE MODEL_REACH_GEOM
(
MODEL_REACH_ID NUMBER(9) NOT NULL,
REACH_GEOM MDSYS.SDO_GEOMETRY NOT NULL,
CATCH_GEOM MDSYS.SDO_GEOMETRY NOT NULL,
CUM_CATCH_GEOM MDSYS.SDO_GEOMETRY NOT NULL
)
;

CREATE TABLE MODEL_REACH_TOPO
(
MODEL_REACH_ID NUMBER(9) NOT NULL,
FNODE NUMBER(9),
TNODE NUMBER(9),
HYDSEQ FLOAT NOT NULL,
AIFTRAN FLOAT NOT NULL
)
;

CREATE TABLE REACH_COEF
(
REACH_COEF_ID NUMBER(9) NOT NULL,
ITERATION NUMBER(4) NOT NULL,
INC_DELIVERY DOUBLE PRECISION NOT NULL,
TOTAL_DELIVERY DOUBLE PRECISION NOT NULL,
BOOT_ERROR DOUBLE PRECISION DEFAULT 0 NOT NULL,
MODEL_REACH_ID NUMBER(9) NOT NULL
)
;

CREATE TABLE SOURCE
(
SOURCE_ID NUMBER(9) NOT NULL,
NAME VARCHAR2(60) NOT NULL,
DESCRIPTION CLOB,
SORT_ORDER NUMBER(3) DEFAULT 1 NOT NULL,
SPARROW_MODEL_ID NUMBER(9, 0) NOT NULL
)
;

CREATE TABLE SOURCE_REACH_COEF
(
SOURCE_REACH_COEF_ID NUMBER(9) NOT NULL,
ITERATION NUMBER(4) NOT NULL,
VALUE DOUBLE PRECISION NOT NULL,
SOURCE_ID NUMBER(9) NOT NULL,
MODEL_REACH_ID NUMBER(9) NOT NULL
)
;

CREATE TABLE SOURCE_REACH_PREDICT
(
SOURCE_REACH_PREDICT_ID NUMBER(9) NOT NULL,
ITERATION NUMBER(4) NOT NULL,
INCREMENTAL DOUBLE PRECISION NOT NULL,
CUMULATIVE DOUBLE PRECISION NOT NULL,
SOURCE_ID NUMBER(9) NOT NULL,
MODEL_REACH_ID NUMBER(9) NOT NULL
)
;

CREATE TABLE SOURCE_VALUE
(
SOURCE_VALUE_ID NUMBER(9) NOT NULL,
VALUE DOUBLE PRECISION NOT NULL,
SOURCE_ID NUMBER(9) NOT NULL,
MODEL_REACH_ID NUMBER(9) NOT NULL
)
;

CREATE TABLE SPARROW_MODEL
(
SPARROW_MODEL_ID NUMBER(9, 0) NOT NULL,
IS_APPROVED CHAR(1) DEFAULT 'F' NOT NULL,
IS_PUBLIC CHAR(1) DEFAULT 'F' NOT NULL,
IS_ARCHIVED CHAR(1) DEFAULT 'F' NOT NULL,
NAME VARCHAR2(40) NOT NULL,
DESCRIPTION CLOB,
DATE_ADDED DATE DEFAULT SYSDATE NOT NULL,
CONTACT_ID NUMBER(9) NOT NULL,
ENH_NETWORK_ID NUMBER(9) NOT NULL
)
;

CREATE TABLE TOTAL_PREDICT
(
TOTAL_PREDICT_ID NUMBER(9) NOT NULL,
ITERATION NUMBER(4) NOT NULL,
NO_DECAY_TOTAL DOUBLE PRECISION NOT NULL,
TOTAL DOUBLE PRECISION NOT NULL,
SPARROW_MODEL_ID NUMBER(9, 0) NOT NULL,
MODEL_REACH_ID NUMBER(9) NOT NULL
)
;

ALTER TABLE MODEL_REACH
ADD CONSTRAINT MODEL_REACH_PK PRIMARY KEY
(
MODEL_REACH_ID
)
 ENABLE
;

ALTER TABLE MODEL_REACH
ADD CONSTRAINT MODEL_REACH_UK_IDENTIFIER UNIQUE
(
SPARROW_MODEL_ID,
IDENTIFIER
)
 ENABLE
;

ALTER TABLE MODEL_REACH_GEOM
ADD CONSTRAINT MODEL_REACH_GEOM_PK PRIMARY KEY
(
MODEL_REACH_ID
)
 ENABLE
;

ALTER TABLE MODEL_REACH_TOPO
ADD CONSTRAINT MODEL_REACH_TOPO_PK PRIMARY KEY
(
MODEL_REACH_ID
)
 ENABLE
;

ALTER TABLE REACH_COEF
ADD CONSTRAINT REACH_COEF_FACT_PK PRIMARY KEY
(
REACH_COEF_ID
)
 ENABLE
;

ALTER TABLE REACH_COEF
ADD CONSTRAINT REACH_COEF_UK_VALUE UNIQUE
(
MODEL_REACH_ID,
ITERATION
)
 ENABLE
;

ALTER TABLE SOURCE
ADD CONSTRAINT SOURCE_PK PRIMARY KEY
(
SOURCE_ID
)
 ENABLE
;

ALTER TABLE SOURCE
ADD CONSTRAINT SOURCE_UK_SOURCE_NAME UNIQUE
(
SPARROW_MODEL_ID,
NAME
)
 ENABLE
;

ALTER TABLE SOURCE_REACH_COEF
ADD CONSTRAINT SOURCE_REACH_COEF_PK PRIMARY KEY
(
SOURCE_REACH_COEF_ID
)
 ENABLE
;

ALTER TABLE SOURCE_REACH_COEF
ADD CONSTRAINT SOURCE_REACH_COEF_UK_VALUE UNIQUE
(
MODEL_REACH_ID,
SOURCE_ID,
ITERATION
)
 ENABLE
;

ALTER TABLE SOURCE_REACH_PREDICT
ADD CONSTRAINT SOURCE_REACH_PREDICT_PK PRIMARY KEY
(
SOURCE_REACH_PREDICT_ID
)
 ENABLE
;

ALTER TABLE SOURCE_REACH_PREDICT
ADD CONSTRAINT SOURCE_REACH_PREDICT_UK_VALUE UNIQUE
(
MODEL_REACH_ID,
SOURCE_ID,
ITERATION
)
 ENABLE
;

ALTER TABLE SOURCE_VALUE
ADD CONSTRAINT SOURCE_VALUE_PK PRIMARY KEY
(
SOURCE_VALUE_ID
)
 ENABLE
;

ALTER TABLE SOURCE_VALUE
ADD CONSTRAINT SOURCE_VALUE_UK_VALUE UNIQUE
(
MODEL_REACH_ID,
SOURCE_ID
)
 ENABLE
;

ALTER TABLE SPARROW_MODEL
ADD CONSTRAINT SPARROW_MODEL_PK PRIMARY KEY
(
SPARROW_MODEL_ID
)
 ENABLE
;

ALTER TABLE SPARROW_MODEL
ADD CONSTRAINT SPARROW_MODEL_UK_NAME UNIQUE
(
ENH_NETWORK_ID,
IS_APPROVED,
IS_PUBLIC,
IS_ARCHIVED,
NAME
)
 ENABLE
;

ALTER TABLE TOTAL_PREDICT
ADD CONSTRAINT TOTAL_PREDICT_PK PRIMARY KEY
(
TOTAL_PREDICT_ID
)
 ENABLE
;

ALTER TABLE TOTAL_PREDICT
ADD CONSTRAINT TOTAL_PREDICT_UK_VALUE UNIQUE
(
SPARROW_MODEL_ID,
ITERATION
)
 ENABLE
;

ALTER TABLE MODEL_REACH
ADD CONSTRAINT MODEL_REACH_SPARROW_MODEL_FK FOREIGN KEY
(
SPARROW_MODEL_ID
)
REFERENCES SPARROW_MODEL
(
SPARROW_MODEL_ID
) ENABLE
;

ALTER TABLE MODEL_REACH
ADD CONSTRAINT MODEL_REACH_ENH_REACH_FK FOREIGN KEY
(
ENH_REACH_ID
)
REFERENCES NETWORK.ENH_REACH
(
ENH_REACH_ID
) ENABLE
;

ALTER TABLE MODEL_REACH_GEOM
ADD CONSTRAINT MODEL_REACH_GEOM_FK FOREIGN KEY
(
MODEL_REACH_ID
)
REFERENCES MODEL_REACH
(
MODEL_REACH_ID
) ENABLE
;

ALTER TABLE MODEL_REACH_TOPO
ADD CONSTRAINT MODEL_REACH_TOPO_FK FOREIGN KEY
(
MODEL_REACH_ID
)
REFERENCES MODEL_REACH
(
MODEL_REACH_ID
) ENABLE
;

ALTER TABLE REACH_COEF
ADD CONSTRAINT REACH_COEF_MODEL_REACH_FK FOREIGN KEY
(
MODEL_REACH_ID
)
REFERENCES MODEL_REACH
(
MODEL_REACH_ID
) ENABLE
;

ALTER TABLE SOURCE
ADD CONSTRAINT SOURCE_SPARROW_MODEL_FK FOREIGN KEY
(
SPARROW_MODEL_ID
)
REFERENCES SPARROW_MODEL
(
SPARROW_MODEL_ID
) ENABLE
;

ALTER TABLE SOURCE_REACH_COEF
ADD CONSTRAINT SOURCE_REACH_COEF_SOURCE_FK FOREIGN KEY
(
SOURCE_ID
)
REFERENCES SOURCE
(
SOURCE_ID
) ENABLE
;

ALTER TABLE SOURCE_REACH_COEF
ADD CONSTRAINT SOURCE_REACH_COEF_FK FOREIGN KEY
(
MODEL_REACH_ID
)
REFERENCES MODEL_REACH
(
MODEL_REACH_ID
) ENABLE
;

ALTER TABLE SOURCE_REACH_PREDICT
ADD CONSTRAINT SOURCE_REACH_PREDICT_SOURCE_FK FOREIGN KEY
(
SOURCE_ID
)
REFERENCES SOURCE
(
SOURCE_ID
) ENABLE
;

ALTER TABLE SOURCE_REACH_PREDICT
ADD CONSTRAINT SOURCE_REACH_PREDICT_FK FOREIGN KEY
(
MODEL_REACH_ID
)
REFERENCES MODEL_REACH
(
MODEL_REACH_ID
) ENABLE
;

ALTER TABLE SOURCE_VALUE
ADD CONSTRAINT SOURCE_VALUE_SOURCE_FK FOREIGN KEY
(
SOURCE_ID
)
REFERENCES SOURCE
(
SOURCE_ID
) ENABLE
;

ALTER TABLE SOURCE_VALUE
ADD CONSTRAINT SOURCE_VALUE_MODEL_REACH_FK FOREIGN KEY
(
MODEL_REACH_ID
)
REFERENCES MODEL_REACH
(
MODEL_REACH_ID
) ENABLE
;

ALTER TABLE SPARROW_MODEL
ADD CONSTRAINT SPARROW_MODEL_CONTACT_FK FOREIGN KEY
(
CONTACT_ID
)
REFERENCES NETWORK.CONTACT
(
CONTACT_ID
) ENABLE
;

ALTER TABLE SPARROW_MODEL
ADD CONSTRAINT SPARROW_MODEL_ENH_NETWORK_FK FOREIGN KEY
(
ENH_NETWORK_ID
)
REFERENCES NETWORK.ENH_NETWORK
(
ENH_NETWORK_ID
) ENABLE
;

ALTER TABLE TOTAL_PREDICT
ADD CONSTRAINT TOTAL_PREDICT_MODEL_REACH_FK FOREIGN KEY
(
MODEL_REACH_ID
)
REFERENCES MODEL_REACH
(
MODEL_REACH_ID
) ENABLE
;

ALTER TABLE SPARROW_MODEL
ADD CONSTRAINT SPARROW_MODEL_CHK_IS_APP CHECK
(IS_APPROVED IN ('T','F'))
 ENABLE
;

ALTER TABLE SPARROW_MODEL
ADD CONSTRAINT SPARROW_MODEL_CHK_IS_PUBLIC CHECK
(IS_PUBLIC IN ('T', 'F'))
 ENABLE
;

ALTER TABLE SPARROW_MODEL
ADD CONSTRAINT SPARROW_MODEL_CHK_IS_ARC CHECK
(IS_ARCHIVED IN ('T', 'F'))
 ENABLE
;

CREATE INDEX MODEL_REACH_ENH_REACH_FK_I ON MODEL_REACH (ENH_REACH_ID);

CREATE INDEX REACH_COEF_IT_I ON REACH_COEF (ITERATION);

CREATE INDEX SOURCE_REACH_IT_I ON SOURCE_REACH_COEF (ITERATION);

CREATE INDEX SOURCE_REACH_PREDICT_IT_I ON SOURCE_REACH_PREDICT (ITERATION);

CREATE SEQUENCE MODEL_REACH_SEQ INCREMENT BY 1 START WITH 1 ORDER ;

CREATE SEQUENCE REACH_COEF_SEQ INCREMENT BY 1 START WITH 1 ORDER ;

CREATE SEQUENCE SOURCE_REACH_COEF_SEQ INCREMENT BY 1 START WITH 1 ORDER ;

CREATE SEQUENCE SOURCE_REACH_PREDICT_SEQ INCREMENT BY 1 START WITH 1 ORDER ;

CREATE SEQUENCE SOURCE_SEQ INCREMENT BY 1 START WITH 1 ORDER ;

CREATE SEQUENCE SOURCE_VALUE_SEQ INCREMENT BY 1 START WITH 1 ORDER ;

CREATE SEQUENCE SPARROW_MODEL_SEQ INCREMENT BY 1 START WITH 1 ORDER ;

CREATE SEQUENCE TOTAL_PREDICT_SEQ INCREMENT BY 1 START WITH 1 ORDER ;

COMMENT ON COLUMN MODEL_REACH_TOPO.FNODE IS 'Can be null if no from node'
;

COMMENT ON COLUMN MODEL_REACH_TOPO.TNODE IS 'Can be null if no downstream node'
;

COMMENT ON COLUMN REACH_COEF.BOOT_ERROR IS 'Would 1 be a more reasonable value for this? '
;

