/* MODEL_REACH table geom indexes */
CREATE INDEX MODEL_REACH_REACH_GEOM_I ON MODEL_REACH_GEOM (REACH_GEOM)
	INDEXTYPE IS MDSYS.SPATIAL_INDEX;
	
CREATE INDEX MODEL_REACH_CATCH_GEOM_I ON MODEL_REACH_GEOM (CATCH_GEOM)
	INDEXTYPE IS MDSYS.SPATIAL_INDEX;
	
CREATE INDEX MODEL_REACH_CUM_CATCH_GEOM_I ON MODEL_REACH_GEOM (CUM_CATCH_GEOM)
	INDEXTYPE IS MDSYS.SPATIAL_INDEX;
