/* NOM_REACH table geom indexes */
CREATE INDEX NOM_REACH_REACH_GEOM_I ON NOM_REACH (REACH_GEOM);
	INDEXTYPE IS MDSYS.SPATIAL_INDEX;
	
CREATE INDEX NOM_REACH_CATCH_GEOM_I ON NOM_REACH (CATCH_GEOM);
	INDEXTYPE IS MDSYS.SPATIAL_INDEX;
	
CREATE INDEX NOM_REACH_CUM_CATCH_GEOM_I ON NOM_REACH (CUM_CATCH_GEOM);
	INDEXTYPE IS MDSYS.SPATIAL_INDEX;
	
	

/* ENH_REACH table geom indexes */
CREATE INDEX ENH_REACH_REACH_GEOM_I ON ENH_REACH (REACH_GEOM);
	INDEXTYPE IS MDSYS.SPATIAL_INDEX;
	
CREATE INDEX ENH_REACH_CATCH_GEOM_I ON ENH_REACH (CATCH_GEOM);
	INDEXTYPE IS MDSYS.SPATIAL_INDEX;
	
CREATE INDEX ENH_REACH_CUM_CATCH_GEOM_I ON ENH_REACH (CUM_CATCH_GEOM);
	INDEXTYPE IS MDSYS.SPATIAL_INDEX;
