package gov.usgswim.sparrow.domain;
import lombok.Data;
/**
 * This class efficiently bundles the relevant areas of a single reach
 * @author cschroed
 */
@Data public class ReachAreas {

	//constructor generated by lombok.
	//DO NOT CHANGE property order. Difficult-to-detect logical errors will
	//occur without compiler warning
	private final Double totalContributingArea;
	private final Double totalUpstreamArea;
	private final Double incrementalArea;
}
