<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" version="1.0">
	<xsl:output method="text" version="1.0" encoding="UTF-8" indent="yes"/>
	
	<xsl:template match="/">
##
## This is a file generated by transforming Tomcat's context.xml
## so that the database connection properties may be used by Ant.
## NEVER EVER CHECK THIS INTO SVN or MAKE AVAILABLE to HUDSON!!!!
##

<xsl:apply-templates select="//Resource"/>
	</xsl:template>
	
	<xsl:template match="Resource">
	<!-- <xsl:variable name="dbName" select="fn:substring-after(@name,'/')" />-->
		<xsl:variable name="dbName" select="substring-after(@name,'/')" />
		<xsl:variable name="prefix" select="concat('db.',$dbName)" />

<xsl:value-of select="$prefix"/>.username=<xsl:value-of select="@username"/><xsl:text>
</xsl:text><xsl:value-of select="$prefix"/>.password=<xsl:value-of select="@password"/><xsl:text>
</xsl:text><xsl:value-of select="$prefix"/>.driver=<xsl:value-of select="@driverClassName"/><xsl:text>
</xsl:text><xsl:value-of select="$prefix"/>.connectionURL=<xsl:value-of select="@url"/><xsl:text>
</xsl:text>
	</xsl:template>
</xsl:stylesheet>
