OPTIONS (SKIP=1)
LOAD DATA
INTO TABLE TEMP_ENH_REACH_ATTRIB
TRUNCATE
FIELDS TERMINATED BY X'9'
TRAILING NULLCOLS
(identifier
,FDATE filler
,RESOLUTION filler
,GNIS_ID filler
,REACH_NAME
,REACH_LENGTH ":REACH_LENGTH * 1000"
,REACHCODE filler
,FLOWDIR filler
,WBAREACOMI filler
,FTYPE filler
,FCODE filler
,SHAPE_LENG filler
,ENABLED filler
)